version: '3'

services:
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - POSTGRES_USER=marco
      - POSTGRES_PASSWORD=foobarbaz
      - POSTGRES_HOST=db 
      - POSTGRES_DB=testdb
      - POSTGRES_PORT=5432
    depends_on:
      - db
    ports:
      - '5000:5000'

  db:
    image: postgres:10
    env_file: .env
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    expose:
      - 5432



  

